---
# Any ignore directives should be uncommented in downstream projects to disable
# Dependabot updates for the given dependency. Downstream projects will get
# these updates when the pull request(s) in the appropriate skeleton are merged
# and Lineage processes these changes.

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    labels:
      - bot
      - dependencies
      - rust
    groups:
      cargo-all:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
      - bot
      - dependencies
      - docker
    groups:
      docker-all:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - bot
      - dependencies
      - github-actions
    groups:
      github-actions-all:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - bot
      - dependencies
      - python
    groups:
      pip-all:
        applies-to: version-updates
        patterns:
          - "*"
