---

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "rust :crab:"
    groups:
      cargo-all:
        applies-to: "version-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "github-actions :octocat:"
    groups:
      github-actions-all:
        applies-to: "version-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot :robot:"
      - "dependencies :game_die:"
      - "python :snake:"
    groups:
      pip-all:
        applies-to: "version-updates"
        patterns:
          - "*"
