---
name: "Build"

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types:
      - edited
      - published
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  diagnostics:
    name: "Diagnostics"
    uses: ./.github/workflows/diagnostics.yml

  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  metadata:
    name: "Metadata"
    needs: [config]
    uses: ./.github/workflows/docker-metadata.yml
    with:
      image_name: ${{ needs.config.outputs.image_name }}

  lint:
    name: "Lint"
    needs:
      - config
    uses: ./.github/workflows/common-lint.yml
