---
name: "Build"

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types:
      - edited
      - published
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  lint:
    name: "Lint"
    needs:
      - config
    uses: ./.github/workflows/common-lint.yml
