---
name: Config

permissions: {}

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      platforms:
        description: The platforms to build (JSON array string)
        default: >-
          ["linux/386","linux/amd64","linux/arm/v5","linux/arm/v6",
          "linux/arm/v7","linux/arm/v8","linux/arm64/v8","linux/loong64",
          "linux/mips64le","linux/ppc64le","linux/riscv64","linux/s390x"]
        type: string
    outputs:
      image_name:
        description: The container image name
        value: felddy/reusable-workflow
      platforms:
        description: The platforms to build (JSON array string)
        value: ${{ inputs.platforms }}
      test_platforms:
        description: The platform to use for testing (JSON array string)
        value: '["linux/amd64"]'
jobs:
  config:
    name: Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Configuration workflow"
