---
name: "Config"

on:
  workflow_call:
    inputs:
      platforms:
        description: "The platforms to build (CSV)"
        default: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        required: false
        type: string
    outputs:
      image_name:
        description: "The Docker image name"
        value: felddy/reusable-workflow
      platforms_csv:
        description: "The platforms to build (CSV)"
        value: ${{ inputs.platforms }}
      platforms_json:
        description: "The platforms to build (JSON)"
        value: ${{ jobs.csv-to-json.outputs.json }}

jobs:
  csv-to-json:
    name: "Convert CSV to JSON"
    uses: ./.github/workflows/csv-to-json.yml
    with:
      csv: ${{ inputs.platforms }}
