---
name: "Labels"

on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml
      - .github/workflows/_labels.yml

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read  # for actions/checkout to fetch code
      issues: write  # for crazy-max/ghaction-github-labeler to create, rename, update and delete label
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@3de87da19416edc45c90cd89e7a4ea922a3aae5a
