---
name: CSV to JSON

# This workflow converts a comma-separated list of platforms to a JSON array.

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      csv:
        description: Comma-separated list
        required: true
        type: string
    outputs:
      json:
        description: JSON array
        value: ${{ jobs.convert.outputs.json }}

jobs:
  convert:
    name: Convert platforms CSV to JSON
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.csv-to-json.outputs.json }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # tag=v2.14.2
        with:
          egress-policy: block
          allowed-endpoints: >

      - name: Convert CSV to JSON
        id: csv-to-json
        run: |
          echo "json=$(echo -n ${{ inputs.csv }} | jq --raw-input --compact-output 'split(",")')" >> $GITHUB_OUTPUT
