---
name: "CSV to JSON"

# This workflow converts a comma-separated list of platforms to a JSON array.

on:
  workflow_call:
    inputs:
      csv:
        description: "Comma-separated list"
        required: true
        type: string
    outputs:
      json:
        description: "JSON array"
        value: ${{ jobs.convert.outputs.json }}

jobs:
  convert:
    name: "Convert platforms CSV to JSON"
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.csv-to-json.outputs.json }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10  # tag=v2.8.0
        with:
          egress-policy: block
          allowed-endpoints: >

      - name: Convert CSV to JSON
        id: csv-to-json
        run: |
          echo "json=$(echo -n ${{ inputs.csv }} | jq --raw-input --compact-output 'split(",")')" >> $GITHUB_OUTPUT
