---
name: Diagnostics

# This workflow outputs diagnostic information about the runner and the environment

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: read

jobs:
  diagnostics:
    name: Diagnostics
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # tag=v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            www.githubstatus.com:443

      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@f0ef9e1cf727f9f76f8485f8c525fa03afc4ec02 # tag=v5.0.0
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@4d9eeaf15dd59aa4346919ea84a84ccf514b4db8 # tag=v3.1.0
