---
name: "Diagnostics"

# This workflow outputs diagnostic information about the runner and the environment

on:
  workflow_call:

permissions:
  contents: read

jobs:
  diagnostics:
    name: "Diagnostics"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f  # tag=v2.10.2
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:443
            azure.archive.ubuntu.com:80
            packages.microsoft.com:443
            www.githubstatus.com:443

      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@6aadd1a8de5ca43c8e17a0633ef90e2178da5228  # tag=v4.1.0
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@5355a8e5e6ac5a302e746a1c4b7747a0393863c8  # tag=v2.3.0
