---
name: Publish README

# This reusable workflow publishes the description of a container image to
# DockerHub.

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      # Required inputs
      image_name:
        description: The container image name
        required: true
        type: string
      # Optional inputs
      filepath:
        default: ./README.md
        description: The path to the file to publish
        required: false
        type: string
    secrets:
      docker_password:
        description: The password for the DockerHub account
        required: true
      docker_username:
        description: The username for the DockerHub account
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # tag=v2.14.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # tag=v5.0.0
        with:
          password: ${{ secrets.docker_password }}
          readme-filepath: ${{ inputs.filepath }}
          repository: ${{ inputs.image_name }}
          short-description: ${{ github.event.repository.description }}
          username: ${{ secrets.docker_username }}
