---
name: "Publish README"

# This reusable workflow publishes the description of a Docker image to the
# Docker Hub.

on:
  workflow_call:
    inputs:
      # Required inputs
      image_name:
        description: "The Docker image name"
        required: true
        type: string
      # Optional inputs
      filepath:
        default: ./README.md
        description: "The path to the file to publish"
        required: false
        type: string
    secrets:
      docker_password:
        description: "The password for the Docker hub account"
        required: true
      docker_username:
        description: "The username for the Docker hub account"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4  # tag=v2.7.1
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # tag=v4.1.6

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae  # tag=v4.0.0
        with:
          password: ${{ secrets.docker_password }}
          readme-filepath: ${{ inputs.filepath }}
          repository: ${{ inputs.image_name }}
          short-description: ${{ github.event.repository.description }}
          username: ${{ secrets.docker_username }}
