---
name: "Publish README"

# This reusable workflow publishes the description of a Docker image to the
# Docker Hub.

on:
  workflow_call:
    inputs:
      # Required inputs
      image_name:
        description: "The Docker image name"
        required: true
        type: string
      # Optional inputs
      filepath:
        default: ./README.md
        description: "The path to the file to publish"
        required: false
        type: string
    secrets:
      docker_password:
        description: "The password for the Docker hub account"
        required: true
      docker_username:
        description: "The username for the Docker hub account"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911  # tag=v2.13.0
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # tag=v5.0.0

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77  # tag=v4.0.2
        with:
          password: ${{ secrets.docker_password }}
          readme-filepath: ${{ inputs.filepath }}
          repository: ${{ inputs.image_name }}
          short-description: ${{ github.event.repository.description }}
          username: ${{ secrets.docker_username }}
