---
name: "Generate SBOMs"

# This reusable workflow creates a Software Bill of Materials (SBOM) for a all
# images in a workflow artifact.  It allows the SBOMs to be uploaded as a
# workflow artifact, or uploaded as a release asset.

on:
  workflow_call:
    inputs:
      # Required inputs
      image_artifact_name:
        description: "The name of the artifact containing the image archives (will be cleaned)"
        required: true
        type: string
      # Optional inputs
      artifact_retention_days:
        default: 28
        description: "Number of days to retain the sbom artifacts"
        required: false
        type: number
      sbom_artifact_name:
        default: "sboms"
        description: "The name of the artifact to store the SBOMs (will be cleaned)"
        required: false
        type: string
      syft_version:
        default: "v0.101.0"
        description: "The version of syft to use"
        required: false
        type: string

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  OUTPUT_ARTIFACT_WORK_DIR: /tmp/output-artifact-work

jobs:
  generate-sbom:
    permissions:
      contents: write
    name: "Generate SBOMs"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7  # tag=v2.10.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
            sh -s -- -b /usr/local/bin ${{ inputs.syft_version }}

      - name: Create directories for artifact work
        run: |
          mkdir -p ${{ env.OUTPUT_ARTIFACT_WORK_DIR }}

      - name: Clean variables
        id: clean
        run: |
          # Replace illegal characters in repository name
          echo repository=$(echo "${{ github.repository }}" | sed -e 's/[^a-zA-Z0-9._-]/_/g') >> $GITHUB_OUTPUT
          # Replace illegal characters in ref_name
          echo ref_name=$(echo "${{ github.ref_name }}" | sed -e 's/[^a-zA-Z0-9._-]/_/g') >> $GITHUB_OUTPUT
          # Replace illegal characters in image_artifact_name
          echo image_artifact_name=$(echo "${{ inputs.image_artifact_name }}" | sed -e 's/[^a-zA-Z0-9._-]/_/g') >> $GITHUB_OUTPUT
          # Replace illegal characters in sbom_artifact_name
          echo sbom_artifact_name=$(echo "${{ inputs.sbom_artifact_name }}" | sed -e 's/[^a-zA-Z0-9._-]/_/g') >> $GITHUB_OUTPUT

      - name: Calculate file variables
        # If this is a release, the version will be the clean ref_name.  Otherwise it will be the short SHA.
        id: calc
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            echo version=${{ steps.clean.outputs.ref_name }} >> $GITHUB_OUTPUT
          else
            echo version=$(echo "${{ github.sha }}" | cut -c1-7) >> $GITHUB_OUTPUT
          fi

      - name: Download images artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16  # tag=v4.1.8
        with:
          name: ${{ steps.clean.outputs.image_artifact_name }}

      - name: Generate SBOMs
        run: |
          for image_archive in $(find . -name "*.tar"); do
            platform=$(basename $image_archive .tar)
            filename=${{ steps.clean.outputs.repository }}-${platform}-${{ steps.calc.outputs.version }}-sbom.spdx.json
            echo "::group::Generating SBOM $filename for $image_archive"
            syft --verbose=2 --output spdx-json $image_archive > ${{ env.OUTPUT_ARTIFACT_WORK_DIR }}/$filename
            echo "::endgroup::"
          done

      - name: Upload SBOMs as artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # tag=v4.4.3
        with:
          name: ${{ steps.clean.outputs.sbom_artifact_name }}
          path: ${{ env.OUTPUT_ARTIFACT_WORK_DIR }}
          retention-days: ${{ inputs.artifact_retention_days }}

      # If this is a release, attach the SBOMs as release assets.
      # The gh command requires a repository to be checked out.
      - name: Checkout source
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # tag=v4.2.1

      - name: Upload SBOMs as release assets
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} ${{ env.OUTPUT_ARTIFACT_WORK_DIR }}/* --clobber
